### ISSUE TITLE
Costo de servicios Radiorama

### ISSUE THREAD

**Issue by vguera** [vguera/Radiorama#1]
Crear filtros de acuerdo a los siguientes listas desplegables:

Estado:
     DISTRITO FEDERAL.
     AGUASCALIENTES
     BAJA CALIFORNIA NORTE
     BAJA CALIFORNIA SUR
     CAMPECHE
     COAHUILA
     COLIMA
     CHIAPAS
     CHIHUAHUA
     DURANGO
     GUANAJUATO

Ciudad:
     ENSENADA
     MEXICALI
     TIJUANA

Perfil:
     POP (JUVENIL)
     GRUPERA
     RANCHERA, MEXICANA
     HABLADA NOTICIAS
     INGLES-  ESPAÑOL

Selecciona 
     Baja California 
     Mexicali
     Grupera

Frecuencia:
     AM
     FM
 
y llena control con estos datos:

Muestra resultado de la busqueda:

XEAO	  "RADIO MEXICANA"
XESU	"LA DINAMICA"
XEC	  "RADIO ENCISO"
XEXX	VIDA 
XERCN	UNIRADIO 

Seleciona "LA DINAMICA" y llena control...

"LA DINAMICA"		
SIGLAS: XESU	
POTNCIA 1,000 WATTS
FRECUENCIA: 790	AM
10 $506	
20 $676	
30 $1,018	
40 $1,355	
60 $2,038

Seleciona FM y muestra:

XHMMF	LA BESTIA GRUPERA
XHSOL	VIDA
KMXX	TRICOLOR
KSEH	JOSE FM

Seleciona  JOSE FM

SIGLAS: KSEH
POTENCIA: 50 000 WATTS
FRECUENCIA: 94.5
10 Segundos $1,422
20 Segundos $1,897
30 Segundos $2,844
40 Segundos $3,792
60 Segundos $5,689

**Comment by mauleyzaola** [comment]
Amigo, para cuando necesitas esto maniana? Te tardaste un monton en pasarme la informacion.

**Comment by vguera** [comment]
Pues es que el comentario era que trabajarias 3 horas, asi que aproveche para ir sal super...

Lo vez complejo?

![image](https://cloud.githubusercontent.com/assets/15182375/10900382/a7571e44-81a4-11e5-87c4-a59257b45f73.png)

**Comment by mauleyzaola** [comment]
Lo estoy digiriendo ahora mismo amigo. Si te dije que comenzaria en 3 hrs, pero tambien hace 3 hrs te pedi que hicieras eso que hiciste hace 30 min :smile:

**Comment by mauleyzaola** [comment]
No me respondiste. A que hora lo vas a presentar maniana?

**Comment by vguera** [comment]
a las 13:00, pero lo queremos revisar a las 11:00 para poder hacer ultimas adecuaciones. Lo presentamos con el Director General

**Comment by vguera** [comment]
Por cierto tengo una nueva versión, que hago para subirla?

**Comment by mauleyzaola** [comment]
Ok, entonces lo tendras maniana a las 11:00 hrs. Lo que me va a costar mas trabajo como suele sucederme, es el tema del UI. Es decir, esos controles para seleccionar que son? Dropdowns? Donde iran?

**Comment by mauleyzaola** [comment]
Nueva version? Esto es un repositorio amigo, subela aqui :smile:

**Comment by mauleyzaola** [comment]
Mandamela por email, yo se que git no es lo tuyo. Nada mas mandamela cuanto antes please en un zip.

**Comment by vguera** [comment]
Ok, dame 5 y te la mando.

Gracias

**Comment by mauleyzaola** [comment]
Ok pero que sean 5 de verdad. Ya me iba a subir a cenar amigo. Voy a empezar a trabajar de una vez, porque estoy recordando que maniana tengo una junta a las 9:00 con Takasago.

**Comment by mauleyzaola** [comment]
Ya pasaron 5 min amigo.

**Comment by vguera** [comment]
Ya esta, el tema de estos precios hazlo por fa en la pagina de Servicios

**Comment by mauleyzaola** [comment]
:+1:

**Comment by mauleyzaola** [comment]
La foto del Angel se ve watemalteka amigo, idem la de mision

**Comment by mauleyzaola** [comment]
En verdad quieres que esto salga?

![image](https://cloud.githubusercontent.com/assets/1648558/10900968/7beaa16a-81ac-11e5-98e9-925788dec84d.png)

**Comment by vguera** [comment]
Eso lo editare.

Si son fotos demo...

Gracias

El lunes, 2 de noviembre de 2015, Mauricio Leyzaola <
notifications@github.com> escribió:

> En verdad quieres que esto salga?
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1648558/10900968/7beaa16a-81ac-11e5-98e9-925788dec84d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vguera/Radiorama/issues/1#issuecomment-153233509>.
>


-- 

_____________________________
Vicente Guerra Flores
Movil 5554381378

**Comment by vguera** [comment]
Son dos casos.

Si selecciona:

Baja California Norte
Mexicali
Grupera
AM

Muestra resultado de la busqueda:

XEAO "RADIO MEXICANA"
XESU "LA DINAMICA"
XEC "RADIO ENCISO"
XEXX VIDA 
XERCN UNIRADIO

Seleciona "LA DINAMICA" y llena control...

Donde dice Romantica, Extasis, La mexicana: coloca el tiempo, "Costo 10 segundos", "Costo 2 segundos"...
Donde esta numero de costo, estos costos por tiempo 
10 segundos debe decir $506 
20 segundos debe decir $676
30 segundos debe decir $1018
40 segundos debe decir $1355

Ya no hay otro control, si es posible colocarlo y poner
60 segundos: debe decir $2,038

Repites todos los datos en las cajas
SIGLAS: XESU
POTENCIA 1,000 WATTS
FRECUENCIA: 790 AM

Caso 2

Seleciona FM y muestra:

XHMMF LA BESTIA GRUPERA
XHSOL VIDA
KMXX TRICOLOR
KSEH JOSE FM

Seleciona JOSE FM

Donde dice Romantica, Extasis, La mexicana: coloca el tiempo, "Costo 10 segundos", "Costo 2 segundos"...
Donde esta numero de costo, estos costos por tiempo 
10 segundos debe decir $1,422 
20 segundos debe decir $1,897
30 segundos debe decir $2,844
40 segundos debe decir $3,792

Ya no hay otro control, si es posible colocarlo y poner
60 segundos: debe decir $5,689

Repites estos datos en todas las cajas 
SIGLAS: KSEH
POTENCIA: 50 000 WATTS
FRECUENCIA: 94.5

**Comment by mauleyzaola** [comment]
En que escenario puedo seleccionar `JOSE FM`? No veo ese dato en ningun sitio.

**Comment by mauleyzaola** [comment]
Ah, ya vi donde, ignora mi comentario anterior.

**Comment by vguera** [comment]
OK

**Comment by mauleyzaola** [comment]
Listo amigo.

**Comment by vguera** [comment]
Amigo, dejo de jalar el mapa de google... y baje el sitio, mas no puedo
editarlo. Te puedo marcar para una breve asesoría?

Gracias

2015-11-03 8:04 GMT-06:00 Mauricio Leyzaola <notifications@github.com>:

> Listo amigo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vguera/Radiorama/issues/1#issuecomment-153364105>.
>



-- 

_____________________________
Vicente Guerra Flores
Movil 5554381378

**Comment by vguera** [comment]
Hola vguera/Radiorama,
Tienes un mensaje de Vicente Guerra en IQ Elite. 
Haz clic aquí a.iqelite.com/j/LVIdDm/ike/?hg=JPQp4y57Dv para leer el mensaje 


El equipo de IQ Elite



---------------------------------------------------------------------------
Este mensaje estaba destinado a reply@reply.github.com. Si no deseas seguir recibiendo mensajes de IQ Elite, haz clic en este enlace: a.iqelite.com/common/unsubscribe/?code=24993bdd&email=reply@reply.github.com.&hg=JPQp4y57Dv IQ Elite es un servicio con oficina principal en: C/ Gran de Gràcia 15, 2º 1ª, 08012 Barcelona, España.
---------------------------------------------------------------------------

**Comment by vguera** [comment]
Hola vguera/Radiorama,
Tienes un mensaje de Vicente Guerra en IQ Elite. 
Haz clic aquí a.iqelite.com/j/LVIdDm/cfa/?hg=MYfA5LiusD para leer el mensaje 


El equipo de IQ Elite



---------------------------------------------------------------------------
Este mensaje estaba destinado a reply@reply.github.com. Si no deseas seguir recibiendo mensajes de IQ Elite, haz clic en este enlace: a.iqelite.com/common/unsubscribe/?code=a7a4a85f&email=reply@reply.github.com.&hg=MYfA5LiusD IQ Elite es un servicio con oficina principal en: C/ Gran de Gràcia 15, 2º 1ª, 08012 Barcelona, España.
---------------------------------------------------------------------------
