### ISSUE TITLE
Crear pagina: tarifas

### ISSUE THREAD

**Issue by vguera** [vguera/Radiorama#10]
Clonar del repositorio la página donde se encontraban las Tarifas que era 

http://radiorama.efficatia.net/servicios

y colocarla en nueva pagina de nombre Tarifas

Resultado: Va a haber tres páginas, tarifas, servicios y cobertura.

**Comment by mauleyzaola** [comment]
Duplicado con #8 y ya te la pelaste porque ya termine. Se llamara `costos` en lugar de `tarifas`

**Comment by vguera** [comment]
Gracias amigo!!!

2015-11-09 18:02 GMT-06:00 Mauricio Leyzaola <notifications@github.com>:

> Closed #10 <https://github.com/vguera/Radiorama/issues/10>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vguera/Radiorama/issues/10#event-459501606>.
>



-- 

_____________________________
Vicente Guerra Flores
Movil 5554381378

**Comment by vguera** [comment]
Hola vguera/Radiorama,
Tienes un mensaje de Vicente Guerra en IQ Elite. 
Haz clic aquí a.iqelite.com/j/LVIdDm/7j9/?hg=JPQp4y57Dv para leer el mensaje 


El equipo de IQ Elite



---------------------------------------------------------------------------
Este mensaje estaba destinado a reply@reply.github.com. Si no deseas seguir recibiendo mensajes de IQ Elite, haz clic en este enlace: a.iqelite.com/common/unsubscribe/?code=b3f7ffb8&email=reply@reply.github.com.&hg=JPQp4y57Dv IQ Elite es un servicio con oficina principal en: C/ Gran de Gràcia 15, 2º 1ª, 08012 Barcelona, España.
---------------------------------------------------------------------------
