### ISSUE TITLE
Agregar a las estaciones un campo para streaming

### ISSUE THREAD

**Issue by vguera** [vguera/Radiorama#5]
En http://radiorama.efficatia.net/servicios

Agregar un columna que diga: "Audio" con un icono de Play.

Al dar clic en el icono abrir otro tab en el browser con las url de streaming.

**Comment by mauleyzaola** [comment]
@vguera Coloca aqui la url del archivo de Excel que contiene la informacion de las url de audio

**Comment by vguera** [comment]
Aca se encuentran los datos:

https://www.dropbox.com/s/uxw3w2xixy75p82/Tabla%20Coberturas%20y%20Streaming.xlsx?dl=0

Tiene dos columnas al final, Cobertura y Streaming.

Gracias

**Comment by mauleyzaola** [comment]
PR: #9
