### ISSUE TITLE
Pagina: Coberturura

### ISSUE THREAD

**Issue by vguera** [vguera/Radiorama#7]
Clonar la pagina de servicios.

La idea es la misma, solo que en lugar de la tabla que se encuentra, colocar la que te envío en comentario siguiente. Solo cambia que no requiere traer el URL del streaming y en su lugar datos del que localidades cubre.

En lugar de colocar los cuadros de costos, requiere colocar las siguientes imágenes (solo son dos)

Mexicali - XEAO -> imagen Mexicali.png

![mexicali](https://cloud.githubusercontent.com/assets/15182375/11021427/8d74dc58-8606-11e5-98a6-a324efe1e731.png)

México DF - XEWF -> Imagen 
![df](https://cloud.githubusercontent.com/assets/15182375/11021436/b85bc8d2-8606-11e5-9997-30c7a6533f10.png)

Que serian las únicas dos estaciones con imagen

**Comment by mauleyzaola** [comment]
Duplicado con #6
