### ISSUE TITLE
Cambiar header de tabla

### ISSUE THREAD

**Issue by mauleyzaola** [vguera/Radiorama#8]
En http://radiorama.efficatia.net/servicios cambiar `min` por `seg`

![image](https://cloud.githubusercontent.com/assets/1648558/11021738/62d56ec6-8611-11e5-8b42-2f7160190acd.png)

**Comment by vguera** [comment]
Borraste los datos de los costos. El Fix era cambiar Min por Seg solamente.

Ya no existe el tema de los costos en la pagina 

http://radiorama.efficatia.net/servicios

**Comment by mauleyzaola** [comment]
Pues si, no habia ningun dato de costos en el segundo excel que me pasaste. Pon aqui el nuevo acuerdo que llegamos por telefono amigo please.

**Comment by mauleyzaola** [comment]
@vguera Amigo, WTF? Ya termine los cambios antes que tu pongas lo que hay que hacer. En serio que no entiendo donde esta la complicacion de escribir dos lineas.

**Comment by vguera** [comment]
Amigo lo cree aqui:

https://github.com/vguera/Radiorama/issues/10

El 9 de noviembre de 2015, 17:46, Mauricio Leyzaola <
notifications@github.com> escribió:

> Pues si, no habia ningun dato de costos en el segundo excel que me
> pasaste. Pon aqui el nuevo acuerdo que llegamos por telefono amigo please.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vguera/Radiorama/issues/8#issuecomment-155235477>.
>



-- 

_____________________________
Vicente Guerra Flores
Movil 5554381378

**Comment by mauleyzaola** [comment]
Pero tu me quieres volver loco vea? No fuiste tu mismo quien reabrio este ticket?

**Comment by vguera** [comment]
Hola vguera/Radiorama,
Tienes un mensaje de Vicente Guerra en IQ Elite. 
Haz clic aquí a.iqelite.com/j/LVIdDm/lyk/?hg=JPQp4y57Dv para leer el mensaje 


El equipo de IQ Elite



---------------------------------------------------------------------------
Este mensaje estaba destinado a reply@reply.github.com. Si no deseas seguir recibiendo mensajes de IQ Elite, haz clic en este enlace: a.iqelite.com/common/unsubscribe/?code=dfbd70ef&email=reply@reply.github.com.&hg=JPQp4y57Dv IQ Elite es un servicio con oficina principal en: C/ Gran de Gràcia 15, 2º 1ª, 08012 Barcelona, España.
---------------------------------------------------------------------------
